"""empty message

Revision ID: 2d4858551717
Revises: 8e0b6ef36d5a
Create Date: 2020-07-11 23:41:11.924759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4858551717'
down_revision = '8e0b6ef36d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.Integer(), nullable=True),
    sa.Column('business_public_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=160), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
