"""empty message

Revision ID: 8e0b6ef36d5a
Revises: dec65f3fdb41
Create Date: 2020-07-03 01:16:46.950037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0b6ef36d5a'
down_revision = 'dec65f3fdb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_business_email'), 'business', ['email'], unique=True)
    op.create_index(op.f('ix_business_username'), 'business', ['username'], unique=True)
    op.create_table('business_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=True),
    sa.Column('verifier', sa.Boolean(), nullable=True),
    sa.Column('rule1', sa.Boolean(), nullable=True),
    sa.Column('rule2', sa.Boolean(), nullable=True),
    sa.Column('rule3', sa.Boolean(), nullable=True),
    sa.Column('adnl_rule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_details')
    op.drop_index(op.f('ix_business_username'), table_name='business')
    op.drop_index(op.f('ix_business_email'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
